[package]
name = "embrio-native"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"

[dependencies]
embrio-core = { path = "../embrio-core" }

[dependencies.futures-core]
version = "0.3.1"
default-features = false
features = ["unstable", "cfg-target-has-atomic"]
