[package]
name = "embrio-async"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"

[dependencies]
embrio-async-dehygiene = { path = "dehygiene" }

[dev-dependencies]
futures-preview = "0.3.0-alpha.11"
