[package]
name = "embrio-nrf51"
version = "0.1.0"
authors = ["Wim Looman <wim.looman@kiwi.ki>"]

[dependencies]
cortex-m = "0.4.0"
nrf51 = "0.4.0"

[dependencies.embrio-core]
path = "../embrio-core"

[dependencies.futures-core]
git = "https://github.com/Nemo157/futures-rs"
default-features = false
features = ["nightly"]

[dependencies.futures-util]
git = "https://github.com/Nemo157/futures-rs"
default-features = false

[features]
default = []
