[package]
name = "embrio-nrf51"
version = "0.1.0"
authors = ["Wim Looman <wim.looman@kiwi.ki>"]

[dependencies]
cortex-m = "0.4.0"
nrf51 = "0.4.0"
embrio-core = { path = "../embrio-core" }

[dependencies.futures]
git = "https://github.com/rust-lang-nursery/futures-rs"
default-features = false
features = ["nightly"]
