cargo-features = ["edition"]

[package]
name = "local"
version = "0.0.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"
publish = false

[[bin]]
name = "hello"
doc = false

[dependencies]
hello = { path = "../apps/hello" }
embrio-native = { path = "../../embrio-native" }
