cargo-features = ["edition"]

[package]
name = "local"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"
publish = false

[dependencies]
echo = { path = "../apps/echo" }
embrio-native = { path = "../../embrio-native" }
