[package]
name = "embrio-util"
version = "0.1.0"
authors = ["Wim Looman <wim.looman@kiwi.ki>"]

[dependencies]
embrio-core = { path = "../embrio-core" }

[dependencies.futures-core]
git = "https://github.com/Nemo157/futures-rs"
default-features = false
features = ["nightly"]

[dependencies.futures-util]
git = "https://github.com/Nemo157/futures-rs"
default-features = false

[dependencies.futures-stable]
git = "https://github.com/Nemo157/futures-rs"
default-features = false
features = ["nightly"]

[dependencies.futures-await]
git = "https://github.com/Nemo157/futures-await"
default-features = false

[features]
default = []
