[workspace]
members = [
  "apps/hello",
  "local",
  "pca10031",
]

# https://github.com/japaric/bare-metal/pull/10
[patch.crates-io.bare-metal]
git = "https://github.com/Nemo157/bare-metal"
branch = "remove-old-feature"
